### ISSUE TITLE
Translation panel via WebDebugToolbar

### ISSUE THREAD

**Issue by rvanlaak** [Orbitale/TranslationBundle#4]
Would be great to allow a workflow to translate the last action, as is possible via https://github.com/adrianolek/AOTranslationBundle#translations-panel

Is it easy to add the controller functionality as a anel to the Profiler?

**Comment by Pierstoval** [comment]
This bundle's goal is to allow the translations to be also editable in prod, that's why the proposals are to either use the native controller or to use SonataAdmin (we also might soon propose the use of the great EasyAdmin).
 
If we add a panel to the profiler (which sounds really great, thanks for asking) , I fear this would be kind of copying the work of AOTranslationBundle, even if I'm using other behaviors... Don't you think?
 
But this is a good idea indeed. Do you want to help work on it? (we first need to make the travis-ci builds pass again, even though the bundle is working properly)

**Comment by Rvanlaak** [comment]
You are totally right about the copying, so maybe @adrianolek could elaborate on that.

It seems like both bundles tend to do the same (SonataAdmin, Doctrine) but this bundle has some extra features on top of that. Especially dumping the files is great, that allow us to put them under version control. Would be great if notes (supported by XLIFF) could be added via the new translation panel.

**Comment by Pierstoval** [comment]
A note support would be great indeed.
 
I guess we can think about it, with a simple `notes` array in the `Translation` entity.
 
It would need some refactoring in the extractor, because it still uses the native's Symfony extractor, but yet it's a marvelous feature to add!

**Comment by adrianolek** [comment]
Hey, feel free to borrow anything from AOTranslationBundle.

**Comment by Rvanlaak** [comment]
:+1: 

My goal would be to optimize the integration between the `Profiler`, `Translation` and `Debug` component.

**Comment by Pierstoval** [comment]
Ow, I think I won't implement such solution in this bundle, but this Transifex sounds awesome :+1:

**Comment by Rvanlaak** [comment]
Being able to catch all translations from the active action already is a great way to focus on translating a specific page. That is where it lacks in my current translation workflow, not knowing where the translations can be found ;-)

**Comment by Pierstoval** [comment]
I'm gonna work on this in the next weeks, I'm on many projects now ;)

**Comment by Rvanlaak** [comment]
:+1: if you're able to make a flying start with it (eg. lending the @adrianolek code), I'll be able to help you next week.

**Comment by Pierstoval** [comment]
I'm feeling like I'm gonna "abandon" this bundle, because I just found [LexikTranslationBundle](https://github.com/lexik/LexikTranslationBundle) is doing exactly what I wanted for this bundle :)

**Comment by Rvanlaak** [comment]
@Pierstoval maybe you can help us on the https://github.com/lexik/LexikTranslationBundle/tree/list_missing_translations branch to implement some extra features based on the Symfony `2.7` new translations datacollector.

**Comment by Pierstoval** [comment]
I'm gonna check this :)
