### ISSUE TITLE
Add suppport for xliff "notes"

### ISSUE THREAD

**Issue by Pierstoval** [Orbitale/TranslationBundle#5]
See http://symfony.com/blog/new-in-symfony-2-6-added-support-for-xliff-notes

Asked by @Rvanlaak

**Comment by rvanlaak** [comment]
I think that commit on the `dev` branch has never been released right? Especially now I found the `[Not maintained]` label :)

**Comment by Pierstoval** [comment]
Yes, the bundle is unmaintained, there are too many modifications and I think that using database translations is only useful when using "Translatable" objects. Else, it has a huge impact on performances to reload the translations on runtime, especially if the bundle is not used in a "good manner" :)

That's why I decided to stop using it and maintain it, it's more a "strategy" issue: if you need your translations in a database, it means you can use specific entities for this, and if you are using entities, then you can use translatable, which is much better to use than this bundle (because better developed :D )
